name: xvault-ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v4
      - name: Check Vulnerability in Deps (cargo audit)
        run: |
          cargo install cargo-audit --locked
          cargo audit
      - name: Clone tests assets
        run: make test-init-assets
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: |
          cargo install cargo-tarpaulin --locked
          make test-coverage PROFILE=${{ matrix.BUILD_TARGET }}
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}